apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-api.yaml
  - service-api.yaml
  - hpa-api.yaml

commonLabels:
  app: searchop-api
  component: ranking-service

